version: "3"

services:
  app:
    container_name: db-backup
    build:
      context: .
    volumes:
      - ./storage:/app/storage:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
