FROM alpine:3.19
WORKDIR /app

ENV GLIBC_VERSION 2.35-r1

RUN apk update && \
    apk add --no-cache --update unzip curl
    # curl -Lo /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
    # curl -Lo glibc.apk "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk" && \
    # curl -Lo glibc-bin.apk "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk" && \
    # apk add --force-overwrite glibc-bin.apk glibc.apk && \
    # /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib && \
    # echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
    # apk del curl && \
    # rm -rf /var/cache/apk/* glibc.apk glibc-bin.apk

ADD https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip bun-linux-x64.zip
# RUN unzip bun-linux-x64.zip && chmod +x ./bun-linux-x64/bun && mv ./bun-linux-x64/bun /usr/local/bin && rm -rf bun-linux-x64.zip
RUN unzip bun-linux-x64.zip && ls bun-linux-x64 && ./bun-linux-x64/bun --version

RUN chmod +x /usr/local/bin/bun
RUN /usr/local/bin/bun --version

# CMD ["bun", "--version"]

# RUN apk --no-cache add postgresql16-client

# ENTRYPOINT ["bun", "run", "dev"]
