version: "3"

services:
  backend:
    container_name: db-backup-be
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
