FROM oven/bun:alpine

WORKDIR /app

COPY ["package.json", "bun.lockb", "./"]
RUN bun install

# Add db clients
RUN apk --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main add postgresql16-client

ENTRYPOINT ["bun", "run", "dev"]
